# Generated by Django 5.2.12 on 2026-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
