# Generated by Django 5.2.12 on 2026-03-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0001_initial'),
        ('airports', '0001_initial'),
        ('crews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='airlines.airline')),
            ],
            options={
                'ordering': ('registration_number',),
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('gate', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BOARDING', 'Boarding'), ('ON_TIME', 'On Time'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlines.airline')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='airports.airport')),
                ('origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='airports.airport')),
            ],
            options={
                'ordering': ('departure_time',),
            },
        ),
        migrations.CreateModel(
            name='FlightCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_role', models.CharField(max_length=100)),
                ('crew_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_assignments', to='crews.crewprofile')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='flights.flight')),
            ],
            options={
                'ordering': ('flight__departure_time',),
                'unique_together': {('flight', 'crew_profile')},
            },
        ),
    ]
