# Generated by Django 5.2.12 on 2026-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(choices=[('CAPTAIN', 'Captain'), ('FIRST_OFFICER', 'First Officer'), ('CABIN_CREW', 'Cabin Crew'), ('GROUND_STAFF', 'Ground Staff')], max_length=30)),
            ],
            options={
                'ordering': ('employee_id',),
            },
        ),
    ]
